project_id = "qihhgwslsjicjtrqvzsv"

[functions.submit-rental-application]
verify_jwt = false

[functions.export-calendar]
verify_jwt = false

[functions.send-booking-approval-email]
verify_jwt = false

[functions.submit-extension-request]
verify_jwt = false

[functions.mirror-extension-block]
verify_jwt = false

[functions.send-extension-approval-email]
verify_jwt = false

[functions.send-extension-decline-email]
verify_jwt = false

[functions.unit-ical]
verify_jwt = false
